[colors.bright]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xdcdfe4"

[font]
size = 14.0

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.98

[window.dimensions]
columns = 130
lines = 28

[env]
TERM = "xterm-256color"
