let &packpath = substitute(&packpath, "\\.vim", ".config/vim", "g")
let &rtp = substitute(&rtp, "\\.vim", ".config/vim", "g")
set viminfo+=n~/.config/vim/viminfo

" Colors
let &t_8f = "\[38;2;%lu;%lu;%lum"
let &t_8b = "\[48;2;%lu;%lu;%lum"
set tgc
colorscheme nord


set cursorline
hi clear CursorLine
augroup CLClear
    autocmd! ColorScheme * hi clear CursorLine
augroup END
" set cursorcolumn

syntax enable

hi! Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE

set tabstop=4
set shiftwidth=4
set expandtab

set ignorecase
set smartcase

set incsearch
set hlsearch

set rnu

if has('persistent_undo')
   set undofile
   set undodir=$HOME/.vim/undo
endif

autocmd FileType yaml set tabstop=2
autocmd FileType yaml set shiftwidth=2

" Disable ~ files
set nobackup

" Enable filetype plugins, e.g. vim-go, and indent
filetype plugin indent on

" Toggle pastemode, i.e. don't autoindent pastes
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode
