let &rtp = substitute(&rtp, "\\.vim", ".config/vim", "g")
set viminfo+=n~/.config/vim/viminfo
colorscheme nord
set cursorline
hi clear CursorLine
augroup CLClear
    autocmd! ColorScheme * hi clear CursorLine
augroup END
" set cursorcolumn

syntax enable

set tabstop=4
set shiftwidth=4
set expandtab

set ignorecase
set smartcase

set incsearch
set hlsearch

set rnu

if has('persistent_undo')
   set undofile
   set undodir=$HOME/.vim/undo
endif

autocmd FileType yaml set tabstop=2
autocmd FileType yaml set shiftwidth=2

" Disable ~ files
set nobackup
