call plug#begin()

" Plug 'fenetikm/falcon'
Plug 'sonph/onehalf', { 'rtp': 'vim' }

call plug#end()

colorscheme onehalfdark
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
else
  set notermguicolors
endif

set t_Co=256
set cursorline
hi clear CursorLine
augroup CLClear
    autocmd! ColorScheme * hi clear CursorLine
augroup END
" set cursorcolumn

syntax enable

set tabstop=4
set shiftwidth=4
set expandtab

set ignorecase
set smartcase

set incsearch
set hlsearch

set nu

" Disable ~ files
set nobackup

" Toggle pastemode, i.e. don't autoindent pastes
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

set guicursor=
