#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V
# bspc monitor -d code II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a firefox desktop='^2'
