#! /bin/sh

killall -q -w sxhkd
sxhkd &

killall -q -w picom
picom -b &

killall -q -w redshift
redshift-gtk &

# killall only matches 15 chars
killall -q -w lxqt-policykit-
lxqt-policykit-agent &

killall -q -w udiskie
udiskie -t -m nested &

~/.config/polybar/launch.sh dark

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
