#!/bin/zsh

ls_normal='no'
ls_file='fi'
ls_dir='di'
ls_link='ln'
ls_exec='ex'
ls_orphan='or'
ls_missing='mi'

ls_pipe='pi'
ls_door='do'
ls_block='bd'
ls_char='cd'
ls_sock='so'
ls_setuid='su'
ls_setgid='sg'
ls_otherw='ow'

ls_default_colour=0
ls_bold=1
ls_underlined=4
ls_flashing_text=5
ls_reverse_field=7
ls_red=31
ls_green=32
ls_orange=33
ls_blue=34
ls_purple=35
ls_cyan=36
ls_grey=37
ls_black_background=40
ls_red_background=41
ls_green_background=42
ls_orange_background=43
ls_blue_background=44
ls_purple_background=45
ls_cyan_background=46
ls_grey_background=47
ls_dark_grey=90
ls_light_red=91
ls_light_green=92
ls_yellow=93
ls_light_blue=94
ls_light_purple=95
ls_turquoise=96
ls_dark_grey_background=100
ls_light_red_background=101
ls_light_green_background=102
ls_yellow_background=103
ls_light_blue_background=104
ls_light_purple_background=105
ls_turquoise_background=106

LS_COLORS="no=${ls_grey}:fi=${ls_grey}:di=${ls_light_purple}:ln=${ls_underlined};${ls_light_blue}:or=${ls_underlined};${ls_light_red}:mi=${ls_light_red}:ex=${ls_light_green}"
export LS_COLORS
