#
# non-zsh specific
#
#colors
source ~/.config/lscolors

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=10000
setopt incappendhistory autocd notify autopushd pushdsilent nomatch extendedglob histignoredups
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' auto-description '%F{yellow}-- %d --%f'
zstyle ':completion:*' completer _expand _complete _match _correct _approximate _prefix
zstyle ':completion:*' format '%F{blue}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' match-original both
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=long
zstyle ':completion:*' old-list never
zstyle ':completion:*' old-menu false
zstyle ':completion:*' original false
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %l%s'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle :compinstall filename "${HOME}/.config/zsh/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

zstyle ':autocomplete:*' fzf-completion yes
zstyle ':autocomplete:*' min-delay 0.1

# source ${ZDOTDIR}/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Prompt
PROMPT='%F{cyan}%m%f %B%(?.%F{green}√.%F{red}%?)%f%b %B%F{blue}%3~%f%b %(!.#.$) '
RPROMPT='%*'
# End prompt

# Key Bindings
bindkey '^g' accept-search

if [[ "${terminfo[kcbt]}" != "" ]]; then
  bindkey "${terminfo[kcbt]}" reverse-menu-complete   # [Shift-Tab] - move through the completion menu backwards
fi

bindkey '^?' backward-delete-char                     # [Backspace] - delete backward
if [[ "${terminfo[kdch1]}" != "" ]]; then
  bindkey "${terminfo[kdch1]}" delete-char            # [Delete] - delete forward
else
  bindkey "^[[3~" delete-char
  bindkey "^[3;5~" delete-char
  bindkey "\e[3~" delete-char
fi


bindkey "^[[A" up-line-or-search
bindkey "^[[B" down-line-or-search

WORDCHARS='~!#$%^&*(){}[]<>?.+;-'

disable r
# End of Key Bindings

# Completion
setopt ALWAYS_TO_END      # Move cursor to the end of a completed word.
setopt AUTO_LIST          # Automatically list choices on ambiguous completion.
setopt AUTO_MENU
setopt AUTO_REMOVE_SLASH
setopt COMPLETE_IN_WORD
unsetopt flowcontrol
setopt LIST_AMBIGUOUS
unsetopt MENU_COMPLETE
setopt NO_NOMATCH
# End of Completion

# Aliases
alias dog='highlight -O truecolor -s zenburn --force'
alias r='ranger'
alias ls='ls --color=auto'
alias l='ls -lh'
alias ll='ls -alh'
scrot_file () {
    echo "$(xdg-user-dir PICTURES)/scrot/$(date +%F_%T).png"
}
alias scrot_full="scrot $(scrot_file)"
alias scrot_select="scrot -s $(scrot_file)"
alias beep="paplay /usr/share/sounds/gnome/default/alerts/glass.ogg"
# End of Aliases

if [ -f ${ZDOTDIR}/work.zsh ]; then
    source ${ZDOTDIR}/work.zsh
fi

if which opam > /dev/null; then
    eval $(opam env)
fi

# Plugins
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'
source /usr/share/doc/fzf/examples/completion.zsh
# source ${ZDOTDIR}/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# End of Plugins

